apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
  annotations:
    # Usar o AWS Load Balancer Controller
    #service.beta.kubernetes.io/aws-load-balancer-type: "external"
    # Especificar o uso de um NLB
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    # Configuração para NLB interno/privado
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    # Habilitar cross-zone load balancing para alta disponibilidade
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    # Configuração de health check do NLB
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  #externalTrafficPolicy: Local  # Preserva o IP de origem do cliente
