apiVersion: v1
kind: Service
metadata:
  namespace: backend
  name: backend-service
  annotations:
    # Para usar um ALB
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # Network Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-internal: "true" # Tornando-o interno à VPC
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 80
