AWSTemplateFormatVersion: "2010-09-09"
Description: >
  ECR repositories for the feature toggle demo backend and frontend images.

Resources:
  BackendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: backend
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageTagMutability: IMMUTABLE

  FrontendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: frontend
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageTagMutability: IMMUTABLE

Outputs:
  BackendRepositoryUri:
    Value: !GetAtt BackendRepository.RepositoryUri
  FrontendRepositoryUri:
    Value: !GetAtt FrontendRepository.RepositoryUri
